version: "3"

vars:
  PACKAGES: fish git kitty devbox
  DOTFILES_DIR: "{{.ROOT_DIR}}"
  VSCODE_DIR: '{{if eq OS "darwin"}}{{.HOME}}/Library/Application Support/Code/User{{else}}{{.HOME}}/.config/Code/User{{end}}'
  UV_TOOLS: harlequin

tasks:
  bootstrap:
    desc: Full setup on a new machine
    cmds:
      - task: bootstrap:deps
      - task: dotfiles:install
      - task: vscode:install
      - task: devbox:install
      - task: uv:tools

  bootstrap:deps:
    desc: Install core dependencies
    cmds:
      - task: bootstrap:deps:{{if eq OS "darwin"}}mac{{else}}linux{{end}}
    status:
      - command -v stow
      - command -v fish

  bootstrap:deps:mac:
    internal: true
    cmds:
      - brew install stow fish kitty

  bootstrap:deps:linux:
    internal: true
    cmds:
      - sudo apt update && sudo apt install -y stow fish

  dotfiles:install:
    desc: Symlink all dotfiles
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - task: dotfiles:clean
      - for: { var: PACKAGES }
        cmd: stow -t $HOME {{.ITEM}}

  dotfiles:clean:
    desc: Remove existing files that would conflict with stow
    internal: true
    cmds:
      - for: { var: PACKAGES }
        cmd: >-
          find {{.ITEM}} -type f | while read f; do
            target="$HOME/${f#{{.ITEM}}/}";
            [ -f "$target" ] && [ ! -L "$target" ] && rm "$target";
            [ -L "$target" ] && [ ! -e "$target" ] && rm "$target";
          done; true

  dotfiles:uninstall:
    desc: Remove all symlinks
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - for: { var: PACKAGES }
        cmd: stow -t $HOME -D {{.ITEM}}
      - stow -t "{{.VSCODE_DIR}}" -D vscode

  dotfiles:reinstall:
    desc: Restow (after adding files)
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - for: { var: PACKAGES }
        cmd: stow -t $HOME -R {{.ITEM}}
      - stow -t "{{.VSCODE_DIR}}" -R vscode

  vscode:install:
    desc: Symlink VS Code settings via stow
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - mkdir -p "{{.VSCODE_DIR}}"
      - task: vscode:clean
      - stow -t "{{.VSCODE_DIR}}" vscode

  vscode:clean:
    desc: Remove existing files that would conflict with stow
    internal: true
    cmds:
      - >-
        find vscode -type f | while read f; do
          target="{{.VSCODE_DIR}}/${f#vscode/}";
          [ -f "$target" ] && [ ! -L "$target" ] && rm "$target";
          [ -L "$target" ] && [ ! -e "$target" ] && rm "$target";
        done; true

  vscode:uninstall:
    desc: Remove VS Code symlinks
    dir: "{{.DOTFILES_DIR}}"
    cmds:
      - stow -t "{{.VSCODE_DIR}}" -D vscode

  devbox:install:
    desc: Install global Devbox packages
    cmds:
      - devbox global install

  uv:tools:
    desc: Install global Python CLI tools via uv
    cmds:
      - for: { var: UV_TOOLS }
        cmd: uv tool install {{.ITEM}}

  uv:tools:uninstall:
    desc: Uninstall all managed UV tools
    cmds:
      - for: { var: UV_TOOLS }
        cmd: uv tool uninstall {{.ITEM}}

  uninstall:
    desc: Remove everything (symlinks, VS Code, UV tools)
    deps: [bootstrap:deps]
    cmds:
      - task: dotfiles:uninstall
      - task: vscode:uninstall
      - task: uv:tools:uninstall

  fish:reload:
    desc: Reload fish config
    cmds:
      - fish -c "source ~/.config/fish/config.fish"

  update:
    desc: Git pull + restow
    cmds:
      - git pull
      - task: dotfiles:reinstall
